version: '3.8'

services:
  web:
    container_name: bios-uin
    image: squizy/bios-test:latest
    env_file: .env
    expose:
      - "8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 app.wsgi:application"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: